"""Core module - events, exceptions, types."""

from app.core.exceptions import (
    CryptoTraderException,
    ConfigurationError,
    PluginError,
    PluginNotFoundError,
    PluginLoadError,
    ExchangeError,
    ExchangeConnectionError,
    ExchangeAuthError,
    ExchangeOrderError,
    ExchangeRateLimitError,
    StrategyError,
    StrategyExecutionError,
    OrderError,
    OrderValidationError,
    OrderExecutionError,
    PositionError,
    PositionNotFoundError,
    RiskError,
    RiskLimitExceededError,
    DatabaseError,
    DataError,
    DataNotFoundError,
)
from app.core.types import (
    Timeframe,
    OrderSide,
    OrderType,
    OrderStatus,
    PositionSide,
    SignalAction,
    Candle,
    Ticker,
    OrderRequest,
    Order,
    Position,
    Signal,
    Balance,
    AccountInfo,
    Trade,
)
from app.core.events import (
    EventType,
    Event,
    EventBus,
    event_bus,
    subscribe,
    unsubscribe,
    publish,
    publish_sync,
)

__all__ = [
    # Exceptions
    "CryptoTraderException",
    "ConfigurationError",
    "PluginError",
    "PluginNotFoundError",
    "PluginLoadError",
    "ExchangeError",
    "ExchangeConnectionError",
    "ExchangeAuthError",
    "ExchangeOrderError",
    "ExchangeRateLimitError",
    "StrategyError",
    "StrategyExecutionError",
    "OrderError",
    "OrderValidationError",
    "OrderExecutionError",
    "PositionError",
    "PositionNotFoundError",
    "RiskError",
    "RiskLimitExceededError",
    "DatabaseError",
    "DataError",
    "DataNotFoundError",
    # Types
    "Timeframe",
    "OrderSide",
    "OrderType",
    "OrderStatus",
    "PositionSide",
    "SignalAction",
    "Candle",
    "Ticker",
    "OrderRequest",
    "Order",
    "Position",
    "Signal",
    "Balance",
    "AccountInfo",
    "Trade",
    # Events
    "EventType",
    "Event",
    "EventBus",
    "event_bus",
    "subscribe",
    "unsubscribe",
    "publish",
    "publish_sync",
]
